// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0pdu9PcUU9_g1ZmqzS3H6ntzLPZj0Y7M',
    appId: '1:206835097238:web:d87a308b3a24448e796cb7',
    messagingSenderId: '206835097238',
    projectId: 'strynesport-624d5',
    authDomain: 'strynesport-624d5.firebaseapp.com',
    storageBucket: 'strynesport-624d5.appspot.com',
    measurementId: 'G-WSHDMRRR0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBacjaQfTabHOM7sk2jDZRVX-fDIleS6OI',
    appId: '1:206835097238:android:214ccd22dc8d5683796cb7',
    messagingSenderId: '206835097238',
    projectId: 'strynesport-624d5',
    storageBucket: 'strynesport-624d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHyLggCAtnuJ0s2VSMY0BOSUKqEGAlLc4',
    appId: '1:206835097238:ios:bb1082b8895abbef796cb7',
    messagingSenderId: '206835097238',
    projectId: 'strynesport-624d5',
    storageBucket: 'strynesport-624d5.appspot.com',
    iosClientId:
        '206835097238-klatolc1rigpsq3vsq7ftre2sua8no84.apps.googleusercontent.com',
    iosBundleId: 'com.example.strynEsport',
  );
}
